/*
 * ****************************************************************************
 * Copyright (c) 2013-2023, PyInstaller Development Team.
 *
 * Distributed under the terms of the GNU General Public License (version 2
 * or later) with exception for distributing the bootloader.
 *
 * The full license is in the file COPYING.txt, distributed with this software.
 *
 * SPDX-License-Identifier: (GPL-2.0-or-later WITH Bootloader-exception)
 * ****************************************************************************
 */

/*
 * Global shared functions used in many bootloader files.
 */

#include <stdarg.h>  /* va_list, va_start(), va_end() */
#include <stdio.h>

#ifdef _WIN32
    #include <windows.h>
    #include <direct.h>
    #include <process.h>
    #include <io.h>
#else
    #include <sys/types.h>
    #include <unistd.h>
#endif

/* On Mac OS X send debug msg also to syslog for windowed app. */
#if defined(__APPLE__) && defined(WINDOWED)
    #include <syslog.h>
#endif

/* PyInstaller headers. */
#include "pyi_global.h"
#include "pyi_utils.h"

/* Text length of MessageBox(). */
#define MBTXTLEN 1024


#if defined(_WIN32) && defined(WINDOWED)

/*
 * Dialogs used in Windows windowed/noconsole builds.
 */

static void
_pyi_show_message_box(const char *msg, const wchar_t *caption, UINT uType)
{
    wchar_t msg_w[MBTXTLEN];

    /* The original message is formatted in UTF-8; convert it to
     * wide-char for MessageBoxW. */
    if (pyi_win32_utf8_to_wcs(msg, msg_w, MBTXTLEN)) {
        MessageBoxW(NULL, msg_w, caption, MB_OK | uType);
    } else {
        /* Conversion failed */
        MessageBoxW(NULL, L"<Failed to convert error message to wide-char string.>", caption, MB_OK | uType);
    }
}

void
pyi_debug_dialog_error(const char *fmt, ...)
{
    char msg[MBTXTLEN];
    va_list args;

    va_start(args, fmt);
    vsnprintf(msg, MBTXTLEN, fmt, args);
    va_end(args);

    _pyi_show_message_box(msg, L"Error", MB_ICONEXCLAMATION);
}

void
pyi_debug_dialog_warning(const char *fmt, ...)
{
    char msg[MBTXTLEN];
    va_list args;

    va_start(args, fmt);
    vsnprintf(msg, MBTXTLEN, fmt, args);
    va_end(args);

    _pyi_show_message_box(msg, L"Warning", MB_ICONWARNING);
}

void
pyi_debug_dialog_winerror(const char * funcname, const char *fmt, ...)
{
    char fullmsg[MBTXTLEN];
    char msg[MBTXTLEN];
    DWORD error_code = GetLastError();
    va_list args;

    va_start(args, fmt);
    vsnprintf(msg, MBTXTLEN, fmt, args);
    va_end(args);

    /* Suppress warnings generated by some mingw64 gcc toolchains;
     * we do not care about truncation here. */
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wformat-truncation"
    snprintf(fullmsg, MBTXTLEN, "%s%s: %s", msg, funcname, pyi_win32_get_winerror_string(error_code));
    #pragma GCC diagnostic pop

    _pyi_show_message_box(fullmsg, L"Error", MB_ICONEXCLAMATION);
}

void
pyi_debug_dialog_perror(const char * funcname, const char *fmt, ...)
{
    char fullmsg[MBTXTLEN];
    char msg[MBTXTLEN];
    va_list args;

    va_start(args, fmt);
    vsnprintf(msg, MBTXTLEN, fmt, args);
    va_end(args);

    /* Suppress warnings generated by some mingw64 gcc toolchains;
     * we do not care about truncation here. */
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wformat-truncation"
    snprintf(fullmsg, MBTXTLEN, "%s%s: %s", msg, funcname, strerror(errno));
    #pragma GCC diagnostic pop

    _pyi_show_message_box(fullmsg, L"Error", MB_ICONEXCLAMATION);
}

/* Emit debug messages (in debug-enabled builds) via OutputDebugString
 * win32 API. */
#ifdef LAUNCH_DEBUG

void
pyi_debug_win32debug(const char *fmt, ...)
{
    char msg[MBTXTLEN];
    wchar_t msg_w[MBTXTLEN];
    va_list args;
    int pid_len;

    /* Add pid to the message */
    pid_len = sprintf(msg, "[%d] ", getpid());

    /* Format message */
    va_start(args, fmt);
    vsnprintf(&msg[pid_len], MBTXTLEN-pid_len, fmt, args);
    va_end(args);

    /* Convert message from UTF-8 to wide-char for OutputDebugStringW */
    if (pyi_win32_utf8_to_wcs(msg, msg_w, MBTXTLEN)) {
        OutputDebugStringW(msg_w);
    } else {
        /* Conversion failed */
        OutputDebugStringW(L"<Failed to convert message to wide-char string.>");
    }
}

void
pyi_debug_win32debug_w(const wchar_t *fmt, ...)
{
    wchar_t msg[MBTXTLEN];
    va_list args;
    int pid_len;

    /* Add pid to the message */
    pid_len = _swprintf(msg, L"[%d] ", getpid());

    /* Format message */
    va_start(args, fmt);
    _vsnwprintf(&msg[pid_len], MBTXTLEN-pid_len, fmt, args);
    va_end(args);

    /* Submit to OutputDebugStringW */
    OutputDebugStringW(msg);
}

#endif /* ifdef LAUNCH_DEBUG */

#else /* defined(_WIN32) && defined(WINDOWED) */


/*
 * Output error and debug messages to console via stderr.
 */

#if defined(_WIN32)

/* Format string in UTF-8, then convert to wide-char and display using
 * fwprintf() */

static void
_pyi_vprintf_to_stderr(const char *fmt, va_list v)
{
    #define VPRINTF_TO_STDERR_BUFSIZE (MBTXTLEN * 2)
    char msg[VPRINTF_TO_STDERR_BUFSIZE];
    wchar_t msg_w[VPRINTF_TO_STDERR_BUFSIZE];

    vsnprintf(msg, VPRINTF_TO_STDERR_BUFSIZE, fmt, v);

    if (pyi_win32_utf8_to_wcs(msg, msg_w, VPRINTF_TO_STDERR_BUFSIZE)) {
        fwprintf(stderr, L"%ls", msg_w);
    } else {
        fwprintf(stderr, L"%ls", L"<Failed to convert message to wide-char string.>\n");
    }
}

#else /* defined(_WIN32) */

/* Use vprintf() */
#define _pyi_vprintf_to_stderr(fmt, v) vfprintf(stderr, fmt, v)

#endif /* defined(_WIN32) */


/*
 * Wrap printing debug messages to console.
 */
void
pyi_debug_printf(const char *fmt, ...)
{
    va_list v;

    /* Print the [PID] prefix */
    fprintf(stderr, "[%d] ", getpid());

    /* Print the message */
    va_start(v, fmt);
    _pyi_vprintf_to_stderr(fmt, v);
    va_end(v);

    /* In macOS .app bundle bootloaders, send a copy of debug message
     * to syslog. This allows to see bootloader debug messages in the
     * Console.app log viewer. */
    /* https://en.wikipedia.org/wiki/Console_(OS_X) */
    /* Levels DEBUG and INFO are ignored so use level NOTICE. */
#if defined(__APPLE__) && defined(WINDOWED)
    va_start(v, fmt);
    vsyslog(LOG_NOTICE, fmt, v);
    va_end(v);
#endif
}

/*
 * Print a debug message, followed by the name of the function that
 * resulted in an error and a textual description of the error, obtained
 * via perror().
 */
void
pyi_debug_perror(const char *funcname, const char *fmt, ...)
{
    va_list v;

    /* Formatted message */
    va_start(v, fmt);
    _pyi_vprintf_to_stderr(fmt, v);
    va_end(v);

    /* Perror-formatted error message */
    perror(funcname);  /* perror() writes to stderr */

#if defined(__APPLE__) && defined(WINDOWED)
    va_start(v, fmt);
    vsyslog(LOG_NOTICE, fmt, v);
    vsyslog(LOG_NOTICE, "%m\n", NULL);  /* %m emits the result of strerror() */
    va_end(v);
#endif
}

/*
 * Print a debug message, followed by the name of the function that
 * resulted in an error and a textual description of the error, obtained
 * via FormatMessage win32 API.
 */
#ifdef _WIN32

static void
_pyi_printf_to_stderr(const char* fmt, ...)
{
    va_list v;

    va_start(v, fmt);
    _pyi_vprintf_to_stderr(fmt, v);
    va_end(v);
}

void
pyi_debug_winerror(const char *funcname, const char *fmt, ...)
{
    va_list v;

    va_start(v, fmt);
    _pyi_vprintf_to_stderr(fmt, v);
    va_end(v);

    _pyi_printf_to_stderr("%s: %s", funcname, pyi_win32_get_winerror_string(GetLastError()));
}

#endif  /* ifdef _WIN32 */

/* Wide-char variant of pyi_debug_printf for printing debug messages to
 * console. */
#ifdef _WIN32

void
pyi_debug_printf_w(const wchar_t *fmt, ...)
{
    va_list v;

    /* Print the [PID] prefix */
    fwprintf(stderr, L"[%d] ", getpid());

    /* Print the message */
    va_start(v, fmt);
    vfwprintf(stderr, fmt, v);
    va_end(v);
}

#endif


#endif  /* defined(_WIN32) && defined(WINDOWED) */
