#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['modulegraph2']

package_data = \
{'': ['*']}

install_requires = \
['typing_extensions', 'objectgraph==1.0a1']

extras_require = \
{":python_version < '3.7'": ['dataclasses']}

setup(name='modulegraph2',
      version='2.0a1',
      description='This package defines a class representing the',
      author='Ronald Oussoren',
      author_email='ronaldoussoren@mac.com',
      url='https://modulegraph2.readthedocs.io/',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6,<4',
     )
