attrs = [('InputSource', 0),
         ('ContentHandler', 0),
         ('ErrorHandler', 0),
         ('SAXException', 0),
         ('SAXNotRecognizedException', 0), 
         ('SAXParseException', 0),
         ('SAXNotSupportedException', 0), 
         ('SAXReaderNotAvailable', 0),
         ('parse', 0),
         ('parseString', 0),
         ('make_parser', 0),
    ]