#!/usr/bin/env bash
set -e

platforms=( \
    manylinux2014_x86_64 musllinux_1_1_x86_64\
    manylinux2014_i686 \
    manylinux2014_aarch64 musllinux_1_1_aarch64 \
    manylinux2014_ppc64le \
    manylinux2014_s390x \
)

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

for platform in "${platforms[@]}"
do
    docker build -t pyi-$platform --build-arg BASE=quay.io/pypa/$platform:2023-08-27-bd7ad21 ./bootloader
    docker run -v "$PWD:/io" -t pyi-$platform
done
