#!/usr/bin/env bash
set -e

platforms=( \
    manylinux2014_x86_64 musllinux_1_1_x86_64\
    manylinux2014_i686 musllinux_1_1_i686 \
    manylinux2014_aarch64 musllinux_1_1_aarch64 \
    manylinux2014_ppc64le musllinux_1_1_ppc64le \
    manylinux2014_s390x musllinux_1_1_s390x \
)

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

for platform in "${platforms[@]}"
do
    docker build -t pyi-$platform --build-arg BASE=quay.io/pypa/$platform ./bootloader
    docker run -v "$PWD:/io" -t pyi-$platform
done
