#! /usr/bin/env python
# encoding: utf-8
#
# Bootloader building script.
#
# Copyright (C) 2010-2012, Martin Zibricky
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA


# TODO Finish migration from waf 1.5 to 1.7 syntax.


top = '.'
out = 'build'


def options(ctx):
    ctx.load('compiler_c')


def configure(ctx):
    ctx.load('compiler_c')
    ctx.check_inline()
    ctx.check_endianness()

    libs = 'dl m z'.split()  # m - math, z - zlib
    for l in libs:
        ctx.check_cc(lib=l)


def build(ctx):
    ctx.program(
        #features = 'aaa',
        source   = ctx.path.ant_glob('common/main.c linux/*.c common/*.c'),
        includes = 'linux common',
        lib      = 'dl m z',
        #cflags   = ['-g'],
        target   = 'run',
    )

