#! /usr/bin/env python
#-----------------------------------------------------------------------------
# Copyright (c) 2014, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------


"""
Bootloader building script.
"""


import os
import platform
import sys

from waflib.Configure import conf
from waflib import Logs


# The following two variables are used by the target "waf dist"
VERSION = ''
APPNAME = ''


# These variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'


# Platform specific switches.
is_win = platform.system() == 'Windows'
is_darwin = platform.system() == 'Darwin'
is_linux = platform.system() == 'Linux'
# TODO find out proper value for AIX/Solaris
is_solar = platform.system() == 'Solaris'
is_aix = platform.system() == 'AIX'


# Build variants of bootloader.
# PyInstaller provides debug/release bootloaders and console/windowed
# variants.
# Every variant has different exe name.
variants = {
    'debug': 'run_d',
    'debugw': 'runw_d',
    'release': 'run',
    'releasew': 'runw',
}


# TODO use following variable only on darwin and for 32bit loader.
# TODO Do we still need this variable on OS X?
# OS X 10.6 might not understand some load commands.
# The following variable fixes 10.6 compatibility.
os.environ['MACOSX_DEPLOYMENT_TARGET'] = '10.6'


# TODO strip created binaries.


def architecture():
    """
    on 64bit Mac function platform.architecture() returns 64bit even
    for 32bit Python. This is the workaround for this.
    """
    if is_darwin and sys.maxsize <= 3**32:
        return '32bit'
    else:
        return platform.architecture()[0]  # 32bit or 64bit


def machine():
    """
    Differenciate path to bootloader with machine name if necessary.

    Machine name in bootloader is necessary only for non-x86 architecture.
    """
    mach = None  # Assume x86/x86_64 machine.
    # Different name for arm is necessary.
    if platform.machine().startswith('arm'):
        mach = 'arm'
    return mach


def options(ctx):
    ctx.load('compiler_c')

    ctx.add_option('--debug',
                   action='store_true',
                   help='Include debugging info for GDB.',
                   default=False,
                   dest='debug')
    ctx.add_option('--leak-detector',
                   action='store_true',
                   help='Link with Boehm garbage collector to detect memory leaks.',
                   default=False,
                   dest='boehmgc')
    ctx.add_option('--clang',
                   action='store_true',
                   help='Try to find clang C compiler instead of gcc.',
                   default=False,
                   dest='clang')

    if is_linux:
        ctx.add_option('--no-lsb',
                       action='store_true',
                       help='Prevent building LSB (Linux Standard Base) bootloader.',
                       default=False,
                       dest='nolsb')
        ctx.add_option('--lsbcc-path',
                       action='store',
                       help='Path where to look for lsbcc. By default PATH is '
                            'searched for lsbcc otherwise is tried file '
                            '/opt/lsb/bin/lsbcc. [Default: lsbcc]',
                       default=None,
                       dest='lsbcc_path')
        ctx.add_option('--lsb-target-version',
                       action='store',
                       help='Specify LSB target version [Default: 4.0]',
                       default='4.0',
                       dest='lsb_version')


@conf
def set_lsb_compiler(ctx):
    """
    Build LSB (Linux Standard Base) bootloader.

    LSB bootloader allows to build bootloader binary that is compatible
    with almost every Linux distribution.
    'lsbcc' just wraps gcc in a special way.
    """
    Logs.pprint('CYAN', 'Building LSB (Linux Standard Base) bootloader.')
    lsb_paths = ['/opt/lsb/bin']
    if ctx.options.lsbcc_path:
        lsb_paths.insert(0, ctx.options.lsbcc_path)
    try:
        ctx.find_program('lsbcc', var='LSBCC', path_list=lsb_paths)
    except ctx.errors.ConfigurationError:
        # Fail hard and print warning if lsbcc is not available.
        #if not ctx.env.LSBCC:
        ctx.fatal('RED', 'LSB (Linux Standard Base) tools >= 4.0 are '
                  'required.\nTry --no-lsb option if not interested in '
                  'building LSB binary.')

    # lsbcc as CC compiler
    ctx.env.append_value('CFLAGS', '--lsb-cc=%s' % ctx.env.CC[0])
    ctx.env.append_value('LINKFLAGS', '--lsb-cc=%s' % ctx.env.CC[0])
    ctx.env.CC = ctx.env.LSBCC
    ctx.env.LINK_CC = ctx.env.LSBCC
    ## check LSBCC flags
    # --lsb-besteffort - binary will work on platforms without LSB stuff
    # --lsb-besteffort - available in LSB build tools >= 4.0
    ctx.check_cc(ccflags='--lsb-besteffort',
                 msg='Checking for LSB build tools >= 4.0',
                 errmsg='LSB >= 4.0 is required', mandatory=True)
    ctx.env.append_value('CFLAGS', '--lsb-besteffort')
    ctx.env.append_value('LINKFLAGS', '--lsb-besteffort')
    # binary compatibility with a specific LSB version
    # LSB 4.0 can generate binaries compatible with 3.0, 3.1, 3.2, 4.0
    # however because of using function 'mkdtemp', loader requires
    # using target version 4.0
    lsb_target_flag = '--lsb-target-version=%s' % ctx.options.lsb_version
    ctx.env.append_value('CFLAGS', lsb_target_flag)
    ctx.env.append_value('LINKFLAGS', lsb_target_flag)


@conf
def set_arch_cflags(ctx):
    """
    Set properly architecture flag (32 or 64 bit) cflags for compiler.
    """
    if is_win and ctx.env.CC_NAME == 'msvc':
        if architecture() == '32bit':
            ctx.env.append_value('LINKFLAGS', '/MACHINE:X86')
        elif architecture() == '64bit':
            ctx.env.append_value('LINKFLAGS', '/MACHINE:X64')
        # Enable 64bit porting warnings and other warnings too.
        ctx.env.append_value('CFLAGS', '/W3')
        # We use SEH exceptions in winmain.c; make sure they are activated.
        ctx.env.append_value('CFLAGS', '/EHa')

    # This ensures proper compilation with 64bit gcc and 32bit Python or vice versa.
    else:
        # Option -m32/-m64 has to be passed to cflags and linkflages.
        if architecture() == '32bit':
            ctx.check_cc(ccflags='-m32', msg='Checking for flags -m32')
            ctx.env.append_value('CFLAGS', '-m32')
            ctx.env.append_value('LINKFLAGS', '-m32')
        elif architecture() == '64bit':
            ctx.check_cc(ccflags='-m64', msg='Checking for flags -m64')
            ctx.env.append_value('CFLAGS', '-m64')
            ctx.env.append_value('LINKFLAGS', '-m64')

    # Ensure proper architecture flags on Mac OS X.
    if is_darwin:
        if architecture() == '32bit':
            mac_arch = ['-arch', 'i386']
        else:
            mac_arch = ['-arch', 'x86_64']
        ctx.env.append_value('CFLAGS', mac_arch)
        ctx.env.append_value('CXXFLAGS', mac_arch)
        ctx.env.append_value('LINKFLAGS', mac_arch)


def configure(ctx):
    ctx.msg('Platform', '%s-%s detected' % (platform.system(), architecture()))

    if is_darwin and architecture() == '64bit':
        ctx.msg('CYAN', 'WARNING: Building bootloader for Python 64-bit on Mac OSX')
        ctx.msg('CYAN', 'For 32b-bit bootloader prepend the python command with:')
        ctx.msg('CYAN', 'VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 python')

    if is_win:
        # Load tool to process *.rc* files for C/C++ like icon for exe files.
        ctx.load('winres')
        # We need to pass architecture switch to the 'windres' tool.
        if architecture() == '32bit':
            ctx.env.WINRCFLAGS = ['--target=pe-i386']
        else:
            ctx.env.WINRCFLAGS = ['--target=pe-x86-64']

    # This tool allows reduce the size of executables.
    ctx.load('strip', tooldir='tools')


    ### C compiler

    # Do not embed manifest file when using MSVC (Visual Studio).
    if is_win:
        # Manifest file will be added in the phase of packaging python
        # application by PyInstaller.
        ctx.env.MSVC_MANIFEST = False
    # Allow to use Clang if preferred.
    if ctx.options.clang:
        ctx.load('clang')
    else:
        if is_win:
            # On Windows use only MingW (gcc).
            ctx.load('gcc')
        else:
            ctx.load('compiler_c')  # Any available C compiler.
    # LSB compatible bootloader only for Linux and without cli option --no-lsb.
    if is_linux and not ctx.options.nolsb:
        ctx.set_lsb_compiler()


    # TODO Set proper optimization flags for MSVC (Visual Studio).
    ### C Compiler optimizations.

    if ctx.options.debug:
        # Include gcc debugging information for debugging in GDB.
        ctx.env.append_value('CFLAGS', '-g')
    else:
        ctx.env.append_value('CFLAGS', '-O2')


    ### Defines, Includes

    if is_linux:
        # Make sure we don't use declarations after statement. It breaks
        # MSVC (Visual Studio).
        ctx.env.append_value('CFLAGS', '-Wdeclaration-after-statement')
        ctx.env.append_value('CFLAGS', '-Werror')

    if not is_win:
        # Defines common for Unix and Unix-like platforms.
        # For details see:
        #   http://man.he.net/man7/feature_test_macros
        #
        ## Without these definitions compiling might fail on OSX.
        ctx.env.append_value('DEFINES', '_POSIX_C_SOURCE=200112L')
        # SUS v2 (UNIX 98) definitions.
        #   Mac OS X 10.5 is UNIX 03 compliant.
        ctx.env.append_value('DEFINES', '_XOPEN_SOURCE=500')
        ctx.env.append_value('DEFINES', '_REENTRANT')
        # Function 'mkdtemp' is available only if _BSD_SOURCE is defined.
        ctx.env.append_value('DEFINES', '_BSD_SOURCE')

    if is_win:
        ctx.env.append_value('DEFINES', 'WIN32')
        ctx.env.append_value('CPPPATH', '../zlib')
    if is_solar:
        ctx.env.append_value('DEFINES', 'SUNOS')
    if is_aix:
        ctx.env.append_value('DEFINES', 'AIX')


    ### Libraries

    if is_win:
        ctx.check_cc(lib='user32', mandatory=True)
        ctx.check_cc(lib='comctl32', mandatory=True)
        ctx.check_cc(lib='kernel32', mandatory=True)
        ctx.check_cc(lib='ws2_32', mandatory=True)
    else:
        ctx.check_cc(lib='dl', mandatory=True)
        ctx.check_cc(lib='m', mandatory=True)
        ctx.check_cc(lib='z', mandatory=True)
        # This uses Boehm GC to manage memory - it replaces malloc() / free()
        # functions. Some messages are printed if memory is not deallocated.
        if ctx.options.boehmgc:
            ctx.check_cc(lib='gc', mandatory=True)
            ctx.env.append_value('DEFINES', 'PYI_LEAK_DETECTOR')
            ctx.env.append_value('DEFINES', 'GC_FIND_LEAK')
            ctx.env.append_value('DEFINES', 'GC_DEBUG')
            ctx.env.append_value('DEFINES', 'SAVE_CALL_CHAIN')


    ### CFLAGS

    if is_win and not ctx.env.CC_NAME == 'msvc':
        # Use Visual C++ compatible alignment
        ctx.env.append_value('CFLAGS', '-mms-bitfields')

    if is_darwin:
        ctx.env.append_value('CFLAGS', '-mmacosx-version-min=10.6')

    ctx.set_arch_cflags()

    # On linux link only with needed libraries.
    # -Wl,--as-needed is on some platforms detected during configure but
    # fails during build. (Mac OS X, Solaris, AIX)
    if is_linux and ctx.check_cc(ccflags='-Wl,--as-needed',
                                 msg='Checking for flags -Wl,--as-needed'):
        ctx.env.append_value('LINKFLAGS', '-Wl,--as-needed')


    ### DEBUG and RELEASE environments
    basic_env = ctx.env

    ## setup DEBUG environment
    ctx.setenv('debug', basic_env)  # Ensure env contains shared values.
    debug_env = ctx.env
    # This define enables verbose console output of the bootloader.
    ctx.env.append_value('DEFINES', ['LAUNCH_DEBUG'])
    ctx.env.append_value('DEFINES', 'NDEBUG')

    ## setup windowed DEBUG environment
    ctx.setenv('debugw', debug_env)  # Ensure env contains shared values.
    ctx.env.append_value('DEFINES', 'WINDOWED')
    # For MinGW disables console window on Windows- MinGW option
    if is_win and not ctx.env.CC_NAME == 'msvc':
            # TODO Is it necessary to have -mwindows for C and LINK flags?
            ctx.env.append_value('LINKFLAGS', '-mwindows')
            ctx.env.append_value('CFLAGS', '-mwindows')
    elif is_darwin:
        #conf.env.append_value('CFLAGS', '-I/Developer/Headers/FlatCarbon')
        # To support catching AppleEvents and running as ordinary OSX GUI app,
        # we have to link against the Carbon framework.
        # This linkage only needs to be there for the windowed bootloaders.
        ctx.env.append_value('LINKFLAGS', '-framework')
        ctx.env.append_value('LINKFLAGS', 'Carbon')
        # conf.env.append_value('LINKFLAGS', '-framework')
        # conf.env.append_value('LINKFLAGS', 'ApplicationServices')

    ## setup RELEASE environment
    ctx.setenv('release', basic_env)  # Ensure env contains shared values.
    release_env = ctx.env
    ctx.env.append_value('DEFINES', 'NDEBUG')

    ## setup windowed RELEASE environment
    ctx.setenv('releasew', release_env)  # Ensure env contains shared values.
    ctx.env.append_value('DEFINES', 'WINDOWED')

    # For MinGW disables console window on Windows- MinGW option
    if is_win and not ctx.env.CC_NAME == 'msvc':
            # TODO Is it necessary to have -mwindows for C and LINK flags?
            ctx.env.append_value('LINKFLAGS', '-mwindows')
            ctx.env.append_value('CFLAGS', '-mwindows')
    elif is_darwin:
        # To support catching AppleEvents and running as ordinary OSX GUI app,
        # we have to link against the Carbon framework.
        # This linkage only needs to be there for the windowed bootloaders.
        ctx.env.append_value('LINKFLAGS', '-framework')
        ctx.env.append_value('LINKFLAGS', 'Carbon')
        # TODO Do we need to link with this framework?
        # conf.env.append_value('LINKFLAGS', '-framework')
        # conf.env.append_value('LINKFLAGS', 'ApplicationServices')


# TODO Use 'strip' command to decrease the size of compiled bootloaders.
def build(ctx):
    if not ctx.variant:
        ctx.fatal('Call "python waf all" to compile all bootloaders.')

    exe_name = variants[ctx.variant]
    install_path = os.path.join(os.getcwd(), '../PyInstaller/bootloader',
                                platform.system() + "-" + architecture())
    install_path = os.path.normpath(install_path)

    if machine():
        install_path += '-' + machine()

    if is_win:
        # Use different RC file (icon) for console/windowed mode - remove '_d'
        icon_rc = 'windows/' + exe_name.replace('_d', '') + '.rc'
        # On Windows we need to link library zlib statically.
        ctx.stlib(
            source=ctx.path.ant_glob('zlib/*.c'),
            target='static_zlib',
            name='zlib',
            includes='zlib',
        )
        ctx.program(
            source=ctx.path.ant_glob('%s src/*.c' % icon_rc),
            target=exe_name,
            install_path=install_path,
            use='USER32 COMCTL32 KERNEL32 WS2_32 zlib',
            includes='src windows zlib',
            # Strip final executables to make them smaller.
            features='strip',
        )
    # Linux, Darwin (MacOSX), ...
    else:
        libs = ['DL', 'M', 'Z']  # 'z' - zlib, 'm' - math,
        if ctx.options.boehmgc:
            libs.append('GC')
        ctx.program(
            source=ctx.path.ant_glob('src/*.c'),
            target=exe_name,
            includes='src',
            use=libs,
            install_path=install_path,
            # Strip final executables to make them smaller.
            features='strip',
        )


def all(ctx):
    """
    Do configure, build, install in one step.
    """
    from waflib import Options
    Options.commands = ['distclean', 'configure', 'build_debug', 'build_release']
    # On Windows and Mac OS X we also need console/windowed bootloaders.
    # On other platforms they make no sense.
    if is_win or is_darwin:
        Options.commands += ['build_debugw', 'build_releasew']
    # Install bootloaders.
    Options.commands += ['install_debug', 'install_release']
    if is_win or is_darwin:
        Options.commands += ['install_debugw', 'install_releasew']


# Set up building several variants of bootloader.
from waflib.Build import BuildContext, InstallContext
for x in variants:
    class BootloaderContext(BuildContext):
        cmd = 'build' + '_' + x
        variant = x
    class BootloaderInstallContext(InstallContext):
        cmd = 'install' + '_' + x
        variant = x
