hiddenimports = ['sip',
                 'PyQt4._qt',
                 'PyQt4.QtAssistant',
                 'PyQt4.QtCore',
                 'PyQt4.QtGui',
                 'PyQt4.QtNetwork',
                 'PyQt4.Qt3Support',
                 'PyQt4.QtSql',
                 'PyQt4.QtSvg',
                 'PyQt4.QtTest',
                 'PyQt4.QtSql',
                 'PyQt4.QtXml',
                 'PyQt4.QtWebKit',
                 'PyQt4.QtOpenGL',
                 ]
